// The business-analysis toolkit (docs/ARCHITECTURE.md §78): planning, elicitation, requirements, modelling and
// requirements-management templates, modelled on the structure of the standard BA forms (business analysis plan,
// interview log, data dictionary, requirements review log, risk log, use case validation checklist, FRS, PDD…)
// and the BA diagram set (BPMN, use case, activity, sequence, class, ER, DFD, state, component). Section and table
// layouts follow those forms; the guidance wording is our own.
import type { ProjectDocTemplate } from './project-templates';
import { callout, doc, h, head, hint, ol, p, t, table, tasks, ul } from './template-kit';

const rows = (n: number, cols: number, first: string[] = []) => Array.from({ length: n }, (_, i) => Array.from({ length: cols }, (_, c) => (c === 0 && first[i] !== undefined ? first[i] : '')));
const form = (labels: string[]) => table(['Field', 'Value'], labels.map((l) => [l, '']));
const diagramBox = (what: string) =>
  callout('info', p(t('Diagram', 'bold')), p(`Draw the ${what} in Flow (New → Flow) and link it here, or insert it with Insert → Flow diagram. Keep this page as the explanation of the picture.`));

/** A modelling page: purpose, notation, the diagram, what to describe, and a review checklist. */
const model = (o: { id: string; code: string; name: string; description: string; purpose: string; notation: [string, string][]; describe: string[]; check: string[] }): ProjectDocTemplate => ({
  id: o.id,
  code: o.code,
  name: o.name,
  description: o.description,
  category: 'Modelling',
  build: (title) =>
    doc(
      h(1, title),
      p(t('Model', 'bold'), ` · ${o.name} · Version 0.1 · Status: Draft`),
      h(2, '1. Purpose'),
      hint(o.purpose),
      h(2, '2. Scope'),
      hint('Which process, system or part of it this model covers; what is left out.'),
      h(2, '3. Diagram'),
      diagramBox(o.name.toLowerCase()),
      h(2, '4. Elements'),
      table(['Element', 'Description', 'Notes'], o.describe.map((d) => [d, '', ''])),
      h(2, '5. Notation used'),
      table(['Symbol', 'Meaning'], o.notation.map(([a, b]) => [a, b])),
      h(2, '6. Open questions'),
      ul('…'),
      h(2, '7. Review checklist'),
      tasks(...o.check),
    ),
});

export const BA_TEMPLATES: ProjectDocTemplate[] = [
  // ── Wiki ──────────────────────────────────────────────────────────────────
  {
    id: 'pd-space-home',
    code: 'HOME',
    name: 'Space home',
    description: 'The front page of a space: what it is for and where to start',
    category: 'Planning',
    hidden: true,
    build: (title) =>
      doc(
        h(1, title),
        callout('info', p('Welcome! This space holds the documentation of the team or project: business case, requirements, models, designs, test and delivery documents.')),
        h(2, 'About this space'),
        hint('What the project or team does, who it is for, and the goals.'),
        h(2, 'Where to start'),
        ul('Business: why we do it (business case, vision, scope)', 'Requirements: what we build (BRD, FRD / FRS, SRS, user stories, data dictionary)', 'Modelling: how it works (process, use case and data models)', 'Delivery & Quality: how we check and ship it (test plan, RTM, risks, changes)'),
        h(2, 'Team'),
        table(['Name', 'Role', 'Contact'], rows(3, 3)),
        h(2, 'Key decisions'),
        table(['Date', 'Decision', 'Owner', 'Page'], rows(2, 4)),
      ),
  },

  // ── Planning ──────────────────────────────────────────────────────────────
  {
    id: 'pd-ba-plan',
    code: 'BAP',
    name: 'Business Analysis Plan',
    description: 'How business analysis is done on the project: stakeholders, elicitation, analysis, traceability, evaluation',
    category: 'Planning',
    build: (title) =>
      doc(
        ...head(title, 'Business Analysis Plan'),
        form(['Project name', 'Project number', 'Author', 'Date']),
        h(2, '1. Introduction'),
        hint('Why this plan exists and the business analysis activities it plans.'),
        h(3, 'Inputs · tools & techniques · outputs'),
        table(['Inputs', 'Tools & techniques', 'Outputs'], [['', '', '']]),
        h(2, '2. Stakeholder engagement and communication approach'),
        h(3, '2.1 Stakeholder register'),
        table(['Stakeholder', 'Role', 'Interest', 'Influence', 'Engagement'], rows(3, 5)),
        h(3, '2.2 Stakeholder engagement'),
        h(3, '2.3 Communication approach'),
        hint('Who gets what, when and how — see the Communication Plan.'),
        h(2, '3. Elicitation approach'),
        h(3, '3.1 Finding information'),
        h(3, '3.2 Preparing for elicitation'),
        form(['Objective', 'Participants', 'Questions']),
        h(3, '3.3 Elicitation techniques'),
        table(['Technique', 'Use it for', 'With whom', 'Planned'], [['Interviews', '', '', ''], ['Facilitated workshops', '', '', ''], ['Focus groups', '', '', ''], ['Brainstorming', '', '', ''], ['Questionnaires / surveys', '', '', ''], ['Document analysis', '', '', ''], ['Interface analysis', '', '', ''], ['Prototypes', '', '', ''], ['Observation', '', '', '']]),
        h(2, '4. Analysis approach'),
        h(3, '4.1 Models to create and analyse'),
        h(3, '4.2 Acceptance criteria'),
        h(3, '4.3 Requirements management'),
        ul('Verify requirements', 'Validate requirements', 'Prioritise requirements and other product information'),
        h(3, '4.4 Product risk management'),
        hint('How product risks are identified and analysed.'),
        h(2, '5. Traceability and monitoring approach'),
        h(2, '6. Solution evaluation approach'),
        h(2, 'References'),
        h(2, 'Sign-off'),
        table(['Name', 'Role', 'Date', 'Signature'], rows(2, 4)),
      ),
  },
  {
    id: 'pd-ba-pm-tasks',
    code: 'BAPM',
    name: 'BA and PM Planning Tasks',
    description: 'Who plans what: business analyst and project manager tasks by plan type',
    category: 'Planning',
    build: (title) =>
      doc(
        h(1, title),
        hint('For each plan, write the planning tasks of the business analyst and of the project manager so nothing falls between the two.'),
        table(
          ['Plan type', 'Business analyst planning tasks', 'Project manager planning tasks'],
          ['Scope management', 'Process improvement', 'Schedule management', 'Quality management', 'Communications management', 'Risk management', 'Staffing management', 'Procurement management', 'Cost management'].map((x) => [x, '', '']),
        ),
      ),
  },

  // ── Elicitation ───────────────────────────────────────────────────────────
  {
    id: 'pd-interview-log',
    code: 'IL',
    name: 'Interview Log',
    description: 'One stakeholder interview: objective, questions and answers, materials, summary',
    category: 'Elicitation',
    build: (title) =>
      doc(
        h(1, title),
        form(['Interview date, time, location', 'Stakeholder (interviewee)', 'Job title and role', 'Scribe', 'Objective of the interview']),
        h(2, 'Questions and responses'),
        hint('Mark each answer as a potential requirement (R), an assumption (A) or a constraint (C).'),
        table(['#', 'Question', 'Response', 'R / A / C'], rows(5, 4, ['1', '2', '3', '4', '5'])),
        h(2, 'Materials discussed'),
        hint('Forms, reports, documents, policies, standards or procedures referred to.'),
        h(2, 'Performance-related information'),
        hint('Volumes, capacity, quality expectations.'),
        h(2, 'Summary'),
        h(2, 'Follow-ups'),
        tasks('…'),
      ),
  },
  {
    id: 'pd-interviewee-profile',
    code: 'IP',
    name: 'Interviewee Profile',
    description: 'Prepare an interview: who the person is and how to approach them',
    category: 'Elicitation',
    build: (title) =>
      doc(
        h(1, title),
        form(['Interviewee name', 'Date', 'Job title', 'Key responsibilities (and outputs produced)', 'Communication style']),
        h(2, 'Profile'),
        table(['', 'Low', 'Medium', 'High'], ['Computing experience', 'Experience with the system', 'Knowledge of the problem or opportunity', 'Support for the project'].map((x) => [x, '', '', ''])),
        h(2, 'Comments'),
        hint('Issues and general attitude toward the project.'),
      ),
  },
  {
    id: 'pd-brainstorming',
    code: 'BS',
    name: 'Brainstorming Agenda',
    description: 'A brainstorming session: objectives, participants, ground rules, ideas, priorities',
    category: 'Elicitation',
    build: (title) =>
      doc(
        h(1, title),
        form(['Session objectives', 'Date and place', 'Facilitator', 'Participants']),
        h(2, 'Agenda'),
        table(['Step', 'Time'], [['Introduce rules and objectives', '10 min'], ['Agree the objective', ''], ['Share ideas', '60 min'], ['Prioritise and select requirements', '60 min']]),
        h(2, 'Ground rules'),
        ul('Every idea is valued', 'Stay on the objective', 'Respect and trust', 'No interrupting', 'No right or wrong opinions', 'All questions welcome', 'Keep to the time'),
        h(2, 'Ideas'),
        table(['#', 'Idea', 'Raised by', 'Votes'], rows(5, 4, ['1', '2', '3', '4', '5'])),
        h(2, 'Selected requirements'),
        table(['#', 'Requirement', 'Priority', 'Owner'], rows(3, 4)),
      ),
  },
  {
    id: 'pd-document-analysis',
    code: 'DA',
    name: 'Document Analysis Log',
    description: 'Existing documents reviewed and what each tells us',
    category: 'Elicitation',
    build: (title) =>
      doc(
        h(1, title),
        hint('Relevant information: (a) current problem, issue or constraint · (b) policy, procedure or process · (c) regulation · (d) business rule · (e) potential new requirement · (f) organisational objective or vision.'),
        table(['#', 'Document name', 'Version', 'Date', 'Author', 'Source', 'Location', 'Accuracy / currency', 'Relevant information (a–f)'], rows(4, 9, ['1', '2', '3', '4'])),
      ),
  },

  // ── Requirements ──────────────────────────────────────────────────────────
  {
    id: 'pd-frs',
    code: 'FRS',
    name: 'Functional Requirements Specification',
    description: 'Module by module: features (MoSCoW), business rules, workflows, data forms, roles, messages',
    category: 'Requirements',
    build: (title) =>
      doc(
        ...head(title, 'Functional Requirements Specification'),
        h(3, 'Document properties'),
        form(['Document type', 'Number', 'Version', 'Revision type (major / minor)', 'Status (draft / approved)', 'Created', 'Last update', 'Author']),
        h(3, 'Approvers and reviewers'),
        table(['Role', 'Name', 'Company', 'Approver / mandatory / optional reviewer'], rows(3, 4)),
        h(2, '1. Introduction'),
        h(3, '1.1 Audience and stakeholders'),
        table(['Name', 'Title', 'Area / module', 'Role', 'Company'], rows(2, 5)),
        h(3, '1.2 Sources of requirements'),
        ul('Related documents', 'Workshops, interviews and other sources'),
        h(3, '1.3 Acronyms, abbreviations, definitions'),
        table(['Term', 'Meaning'], rows(2, 2)),
        h(2, '2. Overall description'),
        h(3, '2.1 Overview'),
        h(3, '2.2 Scope'),
        h(3, '2.3 Out of scope'),
        h(3, '2.4 Open items'),
        h(3, '2.5 Assumptions and dependencies'),
        h(2, '3. Solution functionality overview'),
        h(3, '3.1 Solution boundaries'),
        h(2, '4. Roles and responsibilities'),
        table(['Role', 'Description', 'Privileges'], rows(3, 3)),
        h(2, '5. Functional requirements'),
        hint('MoSCoW: Must · Should · Could · Won’t (this time). Repeat 5.n for every module and function.'),
        h(3, '5.1 <Module> — <Function>'),
        h(4, 'Overview'),
        h(4, 'Features'),
        table(['FR ID', 'Description', 'MoSCoW'], [['FR-001', '', 'Must'], ['FR-002', '', 'Should']]),
        h(4, 'Business rules'),
        table(['BR ID', 'Description'], [['BR-001', '']]),
        h(4, 'Process flow'),
        hint('Link the process model (Modelling → BPMN process model).'),
        h(4, 'Workflow details'),
        table(['WF ID', 'Step', 'Step details'], [['WF-001', '1', '']]),
        h(4, 'Main data form'),
        table(['Field', 'Type', 'Mandatory', 'Read only', 'Description'], rows(3, 5)),
        h(4, 'Use cases'),
        form(['Use case name', 'Use case ID', 'Actors', 'Description', 'Pre-conditions', 'Post-conditions', 'Normal flow', 'Alternative flow', 'Exceptions', 'Notes']),
        h(2, '6. System messages'),
        table(['MSG ID', 'Message', 'When it shows'], [['MSG-001', '', '']]),
        h(2, '7. Communication interfaces'),
        h(2, '8. Integration requirements'),
        h(2, '9. Security requirements'),
        h(2, '10. Regulatory requirements'),
        h(2, '11. Testing requirements'),
        h(2, '12. Future modifications foreseen'),
        h(2, 'Sign-off'),
        table(['Name', 'Role', 'Date', 'Signature'], rows(2, 4)),
      ),
  },
  {
    id: 'pd-data-dictionary',
    code: 'DD',
    name: 'Data Dictionary',
    description: 'Every entity and attribute: meaning, type, length, ranges, allowed values',
    category: 'Requirements',
    build: (title) =>
      doc(
        h(1, title),
        hint('One table per entity. Data types: Text, Number, Money, Date (or your own list).'),
        h(2, 'Entity: <name>'),
        p(t('Definition: ', 'bold'), 'what one record of this entity is.'),
        table(['Attribute', 'Description', 'Data type', 'Max length', 'Min value', 'Max value', 'Allowed values'], rows(4, 7)),
        h(2, 'Entity: <name>'),
        table(['Attribute', 'Description', 'Data type', 'Max length', 'Min value', 'Max value', 'Allowed values'], rows(3, 7)),
      ),
  },
  {
    id: 'pd-info-requirements',
    code: 'IRW',
    name: 'Information Requirements Worksheet',
    description: 'The data on each screen or report: labels, types, rules, input / output',
    category: 'Requirements',
    build: (title) =>
      doc(
        h(1, title),
        form(['Screen / report', 'Purpose', 'Users']),
        table(['Data element', 'Screen label', 'Data type', 'Max length', 'Allowed values', 'Mandatory / optional / conditional', 'Input / output / both', 'Description'], rows(5, 8)),
      ),
  },
  {
    id: 'pd-req-attributes',
    code: 'RAT',
    name: 'Requirements Attribute Table',
    description: 'Each requirement with its type, source, release, verification and priority',
    category: 'Requirements',
    build: (title) =>
      doc(
        h(1, title),
        table(['#', 'Description', 'Type', 'Use case ID', 'Source', 'Date identified', 'Planned release', 'Release approver', 'Verification method', 'Test case #', 'Priority'], rows(4, 11, ['REQ-001', 'REQ-002', 'REQ-003', 'REQ-004'])),
      ),
  },
  {
    id: 'pd-req-standards',
    code: 'STD',
    name: 'Standards for Writing Requirements',
    description: 'House rules for good requirements: shall-language, numbering, the qualities to check',
    category: 'Requirements',
    build: (title) =>
      doc(
        h(1, title),
        h(2, 'Writing rules'),
        ul('Use “shall” for what the system must do (“should” and “may” are not requirements)', 'Number every requirement and never reuse a number', 'Keep requirements apart from background and explanation', 'One requirement per statement; keep it short'),
        h(2, 'A good requirement is'),
        table(
          ['Quality', 'Meaning', 'Check'],
          [
            ['Unambiguous', 'Only one reading', 'Would two readers build the same thing?'],
            ['Complete', 'Nothing missing', 'All inputs, outputs, conditions covered'],
            ['Verifiable', 'Can be tested', 'Is there a measurable pass / fail?'],
            ['Consistent', 'No conflicts', 'No clash with other requirements'],
            ['Modifiable', 'Easy to change', 'Stated once, organised, cross-referenced'],
            ['Traceable', 'Origin and use known', 'Source and tests linked'],
            ['Usable in operation', 'Helps maintenance later', 'Still clear after go-live'],
          ],
        ),
        h(2, 'Examples'),
        table(['Weak', 'Better'], [['The system should be fast.', 'The system shall show search results within 2 seconds for 95% of searches.'], ['', '']]),
      ),
  },
  {
    id: 'pd-glossary',
    code: 'GLO',
    name: 'Glossary',
    description: 'Business and analysis terms used on the project, defined once',
    category: 'Requirements',
    build: (title) =>
      doc(
        h(1, title),
        hint('Keep terms in alphabetical order; link pages that use them.'),
        table(
          ['Term', 'Definition'],
          [
            ['Acceptance criteria', 'Conditions a deliverable must meet to be accepted.'],
            ['Activity diagram', 'A model of the flow of activities in a process, with decisions and parallel paths.'],
            ['Alternative flow', 'A path through a use case other than the main success scenario.'],
            ['Business rule', 'A policy or condition that the business must follow.'],
            ['Context diagram', 'The system as one process with the external entities it exchanges data with.'],
            ['CRUD', 'Create, read, update, delete — the basic operations on data.'],
            ['Exception flow', 'What happens in a use case when something goes wrong.'],
            ['Gap analysis', 'Comparing the current state with the desired state to find what is missing.'],
            ['', ''],
          ],
        ),
      ),
  },

  // ── Modelling ─────────────────────────────────────────────────────────────
  model({
    id: 'pd-model-bpmn',
    code: 'BPMN',
    name: 'BPMN Process Model',
    description: 'A business process in BPMN 2.0: events, tasks, gateways, pools and lanes',
    purpose: 'Show how work flows through the business: who does what, in which order, with which decisions and hand-offs.',
    notation: [
      ['Start / intermediate / end event (circle)', 'Something happens: the process starts, waits (timer, message) or ends'],
      ['Task (rounded rectangle)', 'A unit of work; a sub-process has a + marker'],
      ['Exclusive gateway (diamond ×)', 'One path is taken, depending on a condition'],
      ['Parallel gateway (diamond +)', 'All paths run at the same time / wait for all'],
      ['Inclusive gateway (diamond ○)', 'One or more paths are taken'],
      ['Sequence flow (solid arrow)', 'Order of activities inside a pool'],
      ['Message flow (dashed arrow)', 'Messages between pools (organisations)'],
      ['Pool / lane', 'Participant / role responsible for the activities in it'],
      ['Data object, group, annotation', 'Information used, grouping, comments'],
    ],
    describe: ['Participants (pools / lanes)', 'Trigger (start event)', 'Main steps', 'Decisions (gateways)', 'Exceptions and timers', 'Outcome (end events)'],
    check: ['Every path ends in an end event', 'Gateways are labelled with the question; flows with the answer', 'Each task starts with a verb', 'Lanes match real roles', 'Message flows only cross pools'],
  }),
  model({
    id: 'pd-model-usecase',
    code: 'UCD',
    name: 'Use Case Diagram',
    description: 'Actors, use cases and the system boundary',
    purpose: 'Show who uses the system and for which goals, and where the system boundary is.',
    notation: [
      ['Actor (stick figure)', 'A person or system outside the boundary: primary, supporting or offstage'],
      ['Use case (ellipse)', 'A goal the actor reaches with the system'],
      ['System boundary (box)', 'What is inside the system'],
      ['Association (line)', 'The actor takes part in the use case'],
      ['«include»', 'A use case always uses another'],
      ['«extend»', 'A use case optionally adds to another'],
      ['Generalisation (hollow arrow)', 'A specialised actor or use case'],
    ],
    describe: ['Actors and their goals', 'Use cases (name, ID)', 'Includes / extends', 'System boundary'],
    check: ['Use case names are verb + object', 'Every use case has at least one actor', 'Every use case has a description page (Use Case Specification)', 'No design detail in the diagram'],
  }),
  model({
    id: 'pd-model-activity',
    code: 'AD',
    name: 'Activity Diagram',
    description: 'The flow of activities of a process or use case, with decisions and parallel work',
    purpose: 'Show the steps of a process or use case and how they depend on each other, including parallel and conditional paths.',
    notation: [
      ['Initial node (filled circle)', 'Where the flow starts'],
      ['Activity / action (rounded rectangle)', 'A step'],
      ['Decision / merge (diamond)', 'Branch on a condition / join the branches again'],
      ['Fork / join (bar)', 'Start parallel paths / wait for all of them'],
      ['Swimlane', 'Who performs the steps'],
      ['Final node (bullseye)', 'Where the flow ends'],
    ],
    describe: ['Start and end', 'Activities', 'Decisions and guards', 'Parallel paths', 'Swimlanes'],
    check: ['Every decision has labelled guards', 'Every fork has a matching join', 'Flows end in a final node'],
  }),
  model({
    id: 'pd-model-sequence',
    code: 'SQD',
    name: 'Sequence Diagram',
    description: 'How participants exchange messages over time in one scenario',
    purpose: 'Show the messages between actors and system parts for one scenario, in time order.',
    notation: [
      ['Lifeline', 'A participant (actor, component, object) over time'],
      ['Message (solid arrow)', 'A call or request'],
      ['Return (dashed arrow)', 'The answer'],
      ['Activation bar', 'The participant is busy'],
      ['alt / opt / loop fragments', 'Alternatives, optional parts, repetition'],
    ],
    describe: ['Scenario', 'Participants', 'Messages in order', 'Alternatives and loops'],
    check: ['One scenario per diagram', 'Message names match API or operation names', 'Every request has its answer'],
  }),
  model({
    id: 'pd-model-class',
    code: 'CLD',
    name: 'Class Diagram',
    description: 'Classes, attributes, operations and their relationships',
    purpose: 'Describe the static structure of the domain or design: classes, what they hold and how they relate.',
    notation: [
      ['Class (name / attributes / operations)', 'A kind of object'],
      ['Visibility + - # ~', 'Public, private, protected, package'],
      ['Association', 'Objects are connected; with multiplicity (1, 0..1, *)'],
      ['Aggregation (hollow diamond)', 'A whole made of parts that live on their own'],
      ['Composition (filled diamond)', 'Parts that live and die with the whole'],
      ['Generalisation (hollow arrow)', 'Inheritance'],
      ['Interface / realisation', 'A contract and the class that fulfils it'],
    ],
    describe: ['Classes', 'Key attributes', 'Relationships and multiplicities'],
    check: ['Multiplicities on every association', 'Names are nouns from the glossary', 'No duplicated concepts'],
  }),
  model({
    id: 'pd-model-er',
    code: 'ERD',
    name: 'Entity Relationship Diagram',
    description: 'The data model: entities, attributes, keys and relationships',
    purpose: 'Describe the data the solution keeps and how the pieces relate — the base of the database design and the data dictionary.',
    notation: [
      ['Entity (rectangle)', 'A thing we keep data about; a weak entity has a double border'],
      ['Attribute', 'Simple, composite, multivalued, derived or key'],
      ['Relationship (diamond / line)', 'How entities are connected'],
      ['Cardinality', '1:1, 1:N, M:N — or (min, max)'],
      ['Participation', 'Total (every record takes part) or partial'],
      ['Generalisation / specialisation', 'Sub-types of an entity'],
    ],
    describe: ['Entities', 'Primary keys', 'Relationships and cardinality'],
    check: ['Every entity has a key', 'M:N relationships resolved for the physical model', 'Attributes are in the data dictionary'],
  }),
  model({
    id: 'pd-model-dfd',
    code: 'DFD',
    name: 'Data Flow Diagram',
    description: 'How data moves between external entities, processes and data stores',
    purpose: 'Show where data comes from, how it is processed, where it is stored and where it goes — from the context level down.',
    notation: [
      ['Process (circle / rounded box)', 'Turns input data into output data'],
      ['Data flow (arrow)', 'Data moving, with its name'],
      ['Data store (open rectangle)', 'Data kept for later'],
      ['External entity (square)', 'A source or destination outside the system'],
    ],
    describe: ['Context diagram (level 0)', 'Level-1 processes', 'Data stores', 'External entities'],
    check: ['Every process has an input and an output', 'Data flows are named', 'Balanced between levels', 'No flow goes straight from a store to an entity'],
  }),
  model({
    id: 'pd-model-state',
    code: 'STM',
    name: 'State Diagram',
    description: 'The states of an object and the events that move it between them',
    purpose: 'Show the life cycle of one important object (order, request, account): its states and what changes them.',
    notation: [
      ['Initial state (filled circle)', 'Where the life cycle starts'],
      ['State (rounded rectangle)', 'A condition the object is in'],
      ['Transition (arrow)', 'Event [guard] / action that moves to another state'],
      ['Self-transition', 'An event that leaves the state unchanged'],
      ['Final state (bullseye)', 'The end of the life cycle'],
    ],
    describe: ['Object', 'States', 'Events and guards', 'Actions'],
    check: ['Every state can be reached', 'No state without a way out (except final)', 'Transitions are named with their event'],
  }),
  model({
    id: 'pd-model-component',
    code: 'CMP',
    name: 'Component Diagram',
    description: 'The software components of the solution and their interfaces',
    purpose: 'Show the building blocks of the solution and how they depend on each other through interfaces.',
    notation: [
      ['Component', 'A replaceable part of the system'],
      ['Provided interface (lollipop)', 'What a component offers'],
      ['Required interface (socket)', 'What a component needs'],
      ['Assembly connector', 'A required interface wired to a provided one'],
      ['Port', 'An interaction point of a component'],
      ['Dependency (dashed arrow)', 'One component uses another'],
    ],
    describe: ['Components', 'Interfaces', 'External systems'],
    check: ['Every interface has an owner', 'No circular dependencies', 'External systems shown at the edge'],
  }),

  // ── Design ────────────────────────────────────────────────────────────────
  {
    id: 'pd-pdd',
    code: 'PDD',
    name: 'Process Design Document (RPA)',
    description: 'A process to automate: as-is steps, to-be bot process, exceptions, applications, testing',
    category: 'Design',
    build: (title) =>
      doc(
        ...head(title, 'Process Design Document'),
        h(2, '1. Introduction'),
        h(3, '1.1 Purpose of the document'),
        h(3, '1.2 Objectives'),
        h(3, '1.3 Key contacts'),
        table(['Role', 'Name', 'Contact', 'Notes'], [['Process owner', '', '', ''], ['Subject matter expert', '', '', ''], ['Business analyst', '', '', ''], ['Developer', '', '', '']]),
        h(3, '1.4 Prerequisites for automation'),
        h(2, '2. As-is process'),
        h(3, '2.1 Process overview'),
        table(['Item', 'Description'], ['Process full name', 'Area / department', 'Short description', 'Roles involved', 'Schedule (frequency)', 'Items per period', 'Average handling time', 'Peak periods and volume', 'FTEs', 'Exception rate', 'Input data', 'Output data'].map((x) => [x, ''])),
        h(3, '2.2 Applications used'),
        table(['#', 'Application and version', 'Language', 'Thin / thick client', 'Environment / access', 'Comments'], rows(2, 6, ['1', '2'])),
        h(3, '2.3 As-is process map'),
        hint('High-level and detailed map (Modelling → BPMN process model).'),
        h(3, '2.4 Detailed steps'),
        table(['Step', 'Input', 'Description', 'Screen / document', 'Exception handling', 'Business rule'], rows(3, 6, ['1', '2', '3'])),
        h(2, '3. To-be process'),
        h(3, '3.1 To-be process map (bot steps highlighted)'),
        h(3, '3.2 In scope for automation'),
        ol('…'),
        h(3, '3.3 Out of scope'),
        table(['Step', 'Activity', 'Reason', 'Impact on to-be'], rows(1, 4)),
        h(3, '3.4 Business exceptions'),
        table(['BE #', 'Exception', 'Step', 'Parameters', 'Action to be taken'], rows(2, 5, ['BE-1', 'BE-2'])),
        h(3, '3.5 Application errors'),
        table(['E #', 'Error', 'Step', 'Action to be taken'], rows(2, 4, ['E-1', 'E-2'])),
        h(3, '3.6 Reporting'),
        h(2, '4. Development prerequisites'),
        ul('Credentials and asset management', 'Password policies', 'Environments'),
        h(2, '5. Testing'),
        ul('Alpha testing', 'User acceptance test'),
      ),
  },

  // ── Delivery & Quality (requirements management) ─────────────────────────
  {
    id: 'pd-review-log',
    code: 'RRL',
    name: 'Requirements Review Log',
    description: 'A requirements review: participants and every finding with category and priority',
    category: 'Delivery & Quality',
    build: (title) =>
      doc(
        h(1, title),
        form(['Project', 'Document reviewed', 'Version', 'Review date and place']),
        h(2, 'Participants'),
        table(['Name', 'Role'], [['', 'Moderator'], ['', 'Scribe'], ['', 'Reviewer'], ['', 'Peer']]),
        h(2, 'Findings'),
        hint('Category: question / comment, or error / defect. Priority: high, medium, low.'),
        table(['#', 'Page / section', 'Description', 'Category', 'Priority', 'Resolution'], rows(4, 6, ['1', '2', '3', '4'])),
      ),
  },
  {
    id: 'pd-rmp-checklist',
    code: 'RMPC',
    name: 'Requirements Management Plan Checklist',
    description: 'Is the requirements management plan complete?',
    category: 'Delivery & Quality',
    build: (title) =>
      doc(
        h(1, title),
        h(2, 'Introduction'),
        tasks('Purpose', 'Scope', 'Planning considerations', 'Definitions and acronyms'),
        h(2, 'Requirements management'),
        tasks('Stakeholders and their roles', 'How requirements are elicited, analysed and documented', 'Milestones', 'Tasks with resources and effort', 'Tools', 'Assumptions', 'Tracing approach', 'Requirement attributes', 'Reports', 'Metrics'),
        h(2, 'Change management'),
        tasks('Change process steps', 'Roles and responsibilities'),
        h(2, 'Risk management'),
        tasks('Stakeholders involved', 'Preliminary risks'),
        h(2, 'Training and resources'),
        tasks('People and training needed'),
        h(2, 'Communication'),
        tasks('Communication activities and techniques'),
      ),
  },
  {
    id: 'pd-traceability-worksheet',
    code: 'TW',
    name: 'Traceability Worksheet',
    description: 'Which artifacts are traced to which, and how the matrix is kept current',
    category: 'Delivery & Quality',
    build: (title) =>
      doc(
        h(1, title),
        h(2, '1. What is traced to what'),
        table(['From', 'To', 'Why'], [['Business objectives', 'Use cases / features', ''], ['Requirements', 'Design elements', ''], ['Requirements', 'Test cases', ''], ['', '', '']]),
        h(2, '2. How traceability is kept'),
        ul('Number and structure of matrices', 'Size and level of detail', 'Tool (here: issues linked to pages — see the Traceability view of the project)', 'Training', 'Who keeps the RTM current'),
      ),
  },
  {
    id: 'pd-risk-log',
    code: 'RL',
    name: 'Risk Log',
    description: 'Risks with probability, impact, score, owner, response and status',
    category: 'Delivery & Quality',
    build: (title) =>
      doc(
        h(1, title),
        hint('Score = P × I (1–5 each). Responses: avoid, mitigate, transfer, accept. Status: open, closed.'),
        table(['Risk #', 'Description', 'P', 'I', 'Score', 'Identified', 'Owner', 'Possible responses', 'Selected response', 'Status'], rows(4, 10, ['R-1', 'R-2', 'R-3', 'R-4'])),
      ),
  },
  {
    id: 'pd-risk-response',
    code: 'RR',
    name: 'Risk Response Worksheet',
    description: 'One risk in depth: how to prevent it and how to soften its impact',
    category: 'Delivery & Quality',
    build: (title) =>
      doc(
        h(1, title),
        table(['Risk', 'Probability', 'Impact', 'Score'], [['', '', '', '']]),
        h(2, 'Actions to prevent the risk or make it less likely'),
        tasks('…'),
        h(2, 'Actions to lessen the impact if it happens'),
        tasks('…'),
        h(2, 'Trigger and owner'),
        form(['Early warning signs', 'Owner', 'Review date']),
      ),
  },
  {
    id: 'pd-uc-checklist',
    code: 'UCVC',
    name: 'Use Case Validation Checklist',
    description: 'Check a use case specification before sign-off',
    category: 'Delivery & Quality',
    build: (title) =>
      doc(
        h(1, title),
        form(['Use case', 'Version', 'Reviewer', 'Date']),
        h(2, 'General'),
        tasks('Unique name that reflects the purpose', 'All actors listed', 'No ambiguous wording'),
        h(2, 'Pre-conditions'),
        tasks('Stated explicitly', 'Describe the system state, including data that must or must not exist', 'Describe a valid business situation'),
        h(2, 'Basic flow'),
        tasks('Follows the business rules', 'Only relevant steps', 'Events in the right order', 'References its alternate and exception flows', 'Non-functional requirements noted', 'Actor names, not pronouns', 'Present tense', 'No design terms'),
        h(2, 'Alternate flows'),
        tasks('Named', 'Complete', 'Start point stated', 'Last step returns to the basic flow'),
        h(2, 'Exception flows'),
        tasks('Named', 'Start point stated', 'Complete'),
        h(2, 'Post-conditions'),
        tasks('Stated explicitly', 'Describe a valid business situation', 'Describe the end state'),
        h(2, 'After sign-off'),
        tasks('Marked final', 'Traceability updated to test cases', 'Open issues assigned', 'Stored in the repository'),
      ),
  },
];

/** Every business-analysis template, in the order an analyst works (the BA toolkit starter set). */
export const BA_SET = [
  'pd-ba-plan',
  'pd-ba-pm-tasks',
  'pd-stakeholders',
  'pd-comms',
  'pd-interviewee-profile',
  'pd-interview-log',
  'pd-brainstorming',
  'pd-document-analysis',
  'pd-business-case',
  'pd-scope',
  'pd-brd',
  'pd-frs',
  'pd-use-case',
  'pd-data-dictionary',
  'pd-info-requirements',
  'pd-req-attributes',
  'pd-req-standards',
  'pd-glossary',
  'pd-model-bpmn',
  'pd-model-usecase',
  'pd-model-activity',
  'pd-model-er',
  'pd-rmp',
  'pd-rmp-checklist',
  'pd-rtm',
  'pd-traceability-worksheet',
  'pd-review-log',
  'pd-uc-checklist',
  'pd-risk-log',
  'pd-change-request',
  'pd-test-plan',
  'pd-test-cases',
];
